#!/bin/sh
# cleanup leftover rebuild projects after a while
( export accelerate=1; . /home/slowrollbot/code/git/obs/slowroll-tools/tools/osc.sh ;
for p in $(cd state/prj && find -maxdepth 1 -type f -mtime +60 | sed 's/^\.\///' ) ; do echo "Cleaning up $p ..." ; time osc_delete "source/$p?force=1" && rm "stat/prj/$p" ; done )

# cleanup reports after a while, so they don't accumulate and cause disk-full
find state/reports -type f -mtime +60 -delete
